### ISSUE TITLE
[Feature Request]  Config to reverse functionality

### ISSUE THREAD

**Issue by MLMII** [darmiel/relaxed-instabreak#1]
I was wondering if it would be possible to reverse the functionality of the mod where sneaking would use vanilla mechanics and the 'relaxed breaking' was on by default.

Thank you for your time.

**Comment by darmiel** [comment]
Thanks for the idea, this feature is now available in [v1.1.0](https://github.com/darmiel/relaxed-instabreak/releases/tag/v1.1.0)
